[package]
name = "swash-basics"
description = "A very basic example of how to use Swash."
version = "0.1.0"
authors = ["Speykious <speykious@gmail.com>"]
edition = "2021"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
swash = "0.1.17"
